version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node --version
      - npm --version
      - npm ci --no-audit
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: "dist"
