version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist # Vite/CRA defaults to 'dist'/'build' – set accordingly
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
