version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci
  pre_build:
    commands:
      - echo Starting pre-build phase...
      - npm run lint
  build:
    commands:
      - echo Starting build phase...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - "**/*"
  base-directory: "dist"
  discard-paths: no

cache:
  paths:
    - "node_modules/**/*"
