version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Node.js version:"
      - node --version
      - echo "npm version:"
      - npm --version
      - echo "Current directory:"
      - pwd
      - echo "Installing dependencies..."
      - npm ci --no-audit --prefer-offline --verbose
  build:
    commands:
      - echo "Starting build..."
      - npm run build
      - echo "Build completed successfully!"
      - echo "Build artifacts:"
      - ls -la dist/

artifacts:
  files:
    - "**/*"
  base-directory: "dist"
