[build]
  command = "npm ci --legacy-peer-deps && npm run build:check"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_FLAGS = "--no-audit --prefer-offline --legacy-peer-deps"
  CI = "true"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000, immutable"

# Cache configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Build cache
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
